import { Flight } from "@/types"

export const FLIGHTS: Flight[] = [
  {
    id: "del-bom-indigo",
    airline: "IndiGo",
    from: "DEL",
    to: "BOM",
    departure: "06:00 AM",
    duration: "2h 10m",
    stops: 0,
    platforms: [
      {
        platform: "EaseMyTrip",
        price: 3299,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.easemytrip.com",
        isBest: true,
      },
      {
        platform: "MakeMyTrip",
        price: 3549,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.makemytrip.com",
        isBest: false,
      },
      {
        platform: "GoIbibo",
        price: 3799,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.goibibo.com",
        isBest: false,
      },
      {
        platform: "Cleartrip",
        price: 3999,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.cleartrip.com",
        isBest: false,
      },
    ],
    sabsastaScore: {
      total: 96,
      priceScore: 98,
      qualityScore: 92,
      reliabilityScore: 94,
      experienceScore: 90,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Prices on DEL→BOM rise 28% within 72hrs of travel. Book now.",
      confidence: 87,
      priceTrend: "RISING",
      belowAverage: true,
    },
  },
  {
    id: "bom-blr-airindia",
    airline: "Air India",
    from: "BOM",
    to: "BLR",
    departure: "09:30 AM",
    duration: "1h 45m",
    stops: 0,
    platforms: [
      {
        platform: "EaseMyTrip",
        price: 2899,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.easemytrip.com",
        isBest: true,
      },
      {
        platform: "MakeMyTrip",
        price: 3099,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.makemytrip.com",
        isBest: false,
      },
      {
        platform: "GoIbibo",
        price: 3199,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.goibibo.com",
        isBest: false,
      },
      {
        platform: "Cleartrip",
        price: 3299,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.cleartrip.com",
        isBest: false,
      },
    ],
    sabsastaScore: {
      total: 92,
      priceScore: 94,
      qualityScore: 90,
      reliabilityScore: 88,
      experienceScore: 88,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Price below 6-month average. Good deal right now.",
      confidence: 81,
      priceTrend: "STABLE",
      belowAverage: true,
    },
  },
  {
    id: "del-blr-spicejet",
    airline: "SpiceJet",
    from: "DEL",
    to: "BLR",
    departure: "07:15 AM",
    duration: "2h 50m",
    stops: 0,
    platforms: [
      {
        platform: "EaseMyTrip",
        price: 3799,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.easemytrip.com",
        isBest: true,
      },
      {
        platform: "MakeMyTrip",
        price: 4099,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.makemytrip.com",
        isBest: false,
      },
      {
        platform: "GoIbibo",
        price: 4299,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.goibibo.com",
        isBest: false,
      },
      {
        platform: "Cleartrip",
        price: 4499,
        deliveryTime: "Instant",
        inStock: true,
        link: "https://www.cleartrip.com",
        isBest: false,
      },
    ],
    sabsastaScore: {
      total: 88,
      priceScore: 90,
      qualityScore: 84,
      reliabilityScore: 86,
      experienceScore: 84,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "SpiceJet running flash sale. Prices likely to go up tomorrow.",
      confidence: 79,
      priceTrend: "RISING",
      belowAverage: true,
    },
  },
]

export function searchFlights(from: string, to: string): Flight[] {
  return FLIGHTS.filter(
    (f) =>
      f.from.toLowerCase() === from.toLowerCase() &&
      f.to.toLowerCase() === to.toLowerCase()
  )
}