import { Product } from "@/types"

export const PRODUCTS: Product[] = [
  {
    id: "samsung-m35",
    name: "Samsung Galaxy M35 5G (8GB/128GB)",
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80",
    category: "Smartphones",
    platforms: [
      {
        platform: "Flipkart",
        price: 17999,
        originalPrice: 21999,
        deliveryTime: "2 days",
        deliveryFee: 0,
        rating: 4.3,
        inStock: true,
        link: "https://www.flipkart.com/search?q=samsung+galaxy+m35",
        isBest: true,
      },
      {
        platform: "Amazon",
        price: 18499,
        originalPrice: 21999,
        deliveryTime: "1 day",
        deliveryFee: 0,
        rating: 4.3,
        inStock: true,
        link: "https://www.amazon.in/s?k=samsung+galaxy+m35",
        isBest: false,
      },
      {
        platform: "Meesho",
        price: 18299,
        originalPrice: 21999,
        deliveryTime: "4 days",
        deliveryFee: 0,
        rating: 4.1,
        inStock: true,
        link: "https://www.meesho.com/search?q=samsung+m35",
        isBest: false,
      },
      {
        platform: "JioMart",
        price: 19499,
        originalPrice: 21999,
        deliveryTime: "3 days",
        deliveryFee: 0,
        rating: 4.0,
        inStock: true,
        link: "https://www.jiomart.com/search/samsung+m35",
        isBest: false,
      },
    ],
    priceHistory: [
      { week: 1, amazon: 21999, flipkart: 21499 },
      { week: 2, amazon: 21499, flipkart: 20999 },
      { week: 3, amazon: 20999, flipkart: 20499 },
      { week: 4, amazon: 20499, flipkart: 19999 },
      { week: 5, amazon: 19999, flipkart: 19499 },
      { week: 6, amazon: 19499, flipkart: 18999 },
      { week: 7, amazon: 18999, flipkart: 18499 },
      { week: 8, amazon: 18499, flipkart: 17999 },
    ],
    sabsastaScore: {
      total: 94,
      priceScore: 96,
      qualityScore: 88,
      reliabilityScore: 92,
      experienceScore: 90,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Price is at 8-month low. Likely to rise after sale ends.",
      confidence: 87,
      priceTrend: "FALLING",
      belowAverage: true,
    },
    youtubeReviews: [
      {
        channel: "Technical Guruji",
        views: "2.4M",
        sentiment: 92,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=samsung+m35+review",
      },
      {
        channel: "Trakin Tech",
        views: "1.1M",
        sentiment: 88,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=samsung+m35+trakin",
      },
      {
        channel: "Beebom",
        views: "890K",
        sentiment: 85,
        isSponsored: true,
        link: "https://www.youtube.com/results?search_query=samsung+m35+beebom",
      },
    ],
  },
  {
    id: "redmi-note-13",
    name: "Redmi Note 13 (6GB/128GB)",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
    category: "Smartphones",
    platforms: [
      {
        platform: "Flipkart",
        price: 13999,
        originalPrice: 17999,
        deliveryTime: "2 days",
        deliveryFee: 0,
        rating: 4.4,
        inStock: true,
        link: "https://www.flipkart.com/search?q=redmi+note+13",
        isBest: true,
      },
      {
        platform: "Amazon",
        price: 14999,
        originalPrice: 17999,
        deliveryTime: "1 day",
        deliveryFee: 0,
        rating: 4.4,
        inStock: true,
        link: "https://www.amazon.in/s?k=redmi+note+13",
        isBest: false,
      },
      {
        platform: "Meesho",
        price: 14499,
        originalPrice: 17999,
        deliveryTime: "5 days",
        deliveryFee: 0,
        rating: 4.1,
        inStock: true,
        link: "https://www.meesho.com/search?q=redmi+note+13",
        isBest: false,
      },
    ],
    priceHistory: [
      { week: 1, amazon: 17999, flipkart: 16999 },
      { week: 2, amazon: 17499, flipkart: 16499 },
      { week: 3, amazon: 16999, flipkart: 15999 },
      { week: 4, amazon: 16499, flipkart: 15499 },
      { week: 5, amazon: 15999, flipkart: 14999 },
      { week: 6, amazon: 15499, flipkart: 14499 },
      { week: 7, amazon: 14999, flipkart: 13999 },
      { week: 8, amazon: 14999, flipkart: 13999 },
    ],
    sabsastaScore: {
      total: 91,
      priceScore: 94,
      qualityScore: 88,
      reliabilityScore: 90,
      experienceScore: 88,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Price dropped ₹4,000 in 8 weeks. Best value under ₹15K.",
      confidence: 91,
      priceTrend: "FALLING",
      belowAverage: true,
    },
    youtubeReviews: [
      {
        channel: "Technical Guruji",
        views: "3.1M",
        sentiment: 90,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=redmi+note+13+review",
      },
      {
        channel: "Geeky Ranjit",
        views: "1.8M",
        sentiment: 87,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=redmi+note+13+geeky",
      },
      {
        channel: "C4ETech",
        views: "950K",
        sentiment: 82,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=redmi+note+13+c4etech",
      },
    ],
  },
  {
    id: "realme-narzo-70",
    name: "Realme Narzo 70 (8GB/128GB)",
    image: "https://images.unsplash.com/photo-1523206489230-c012c64b2b48?w=800&q=80",
    category: "Smartphones",
    platforms: [
      {
        platform: "Flipkart",
        price: 17499,
        originalPrice: 19999,
        deliveryTime: "2 days",
        deliveryFee: 0,
        rating: 4.2,
        inStock: true,
        link: "https://www.flipkart.com/search?q=realme+narzo+70",
        isBest: true,
      },
      {
        platform: "Amazon",
        price: 17999,
        originalPrice: 19999,
        deliveryTime: "1 day",
        deliveryFee: 0,
        rating: 4.2,
        inStock: true,
        link: "https://www.amazon.in/s?k=realme+narzo+70",
        isBest: false,
      },
    ],
    priceHistory: [
      { week: 1, amazon: 19999, flipkart: 19499 },
      { week: 2, amazon: 19499, flipkart: 18999 },
      { week: 3, amazon: 18999, flipkart: 18499 },
      { week: 4, amazon: 18499, flipkart: 17999 },
      { week: 5, amazon: 17999, flipkart: 17499 },
      { week: 6, amazon: 17999, flipkart: 17499 },
      { week: 7, amazon: 17999, flipkart: 17499 },
      { week: 8, amazon: 17999, flipkart: 17499 },
    ],
    sabsastaScore: {
      total: 86,
      priceScore: 88,
      qualityScore: 84,
      reliabilityScore: 85,
      experienceScore: 82,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Price stable for 4 weeks. Good time to buy before it rises.",
      confidence: 74,
      priceTrend: "STABLE",
      belowAverage: true,
    },
    youtubeReviews: [
      {
        channel: "Trakin Tech",
        views: "1.4M",
        sentiment: 86,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=realme+narzo+70+review",
      },
      {
        channel: "Technical Guruji",
        views: "2.0M",
        sentiment: 84,
        isSponsored: true,
        link: "https://www.youtube.com/results?search_query=realme+narzo+70+technical+guruji",
      },
    ],
  },
  {
    id: "samsung-m14",
    name: "Samsung Galaxy M14 (6GB/128GB)",
    image: "https://images.unsplash.com/photo-1510552776732-01acc9a4cbe5?w=800&q=80",
    category: "Smartphones",
    platforms: [
      {
        platform: "Flipkart",
        price: 12499,
        originalPrice: 14999,
        deliveryTime: "2 days",
        deliveryFee: 0,
        rating: 4.1,
        inStock: true,
        link: "https://www.flipkart.com/search?q=samsung+galaxy+m14",
        isBest: true,
      },
      {
        platform: "Amazon",
        price: 12999,
        originalPrice: 14999,
        deliveryTime: "1 day",
        deliveryFee: 0,
        rating: 4.1,
        inStock: true,
        link: "https://www.amazon.in/s?k=samsung+galaxy+m14",
        isBest: false,
      },
      {
        platform: "JioMart",
        price: 13499,
        originalPrice: 14999,
        deliveryTime: "3 days",
        deliveryFee: 0,
        rating: 3.9,
        inStock: true,
        link: "https://www.jiomart.com/search/samsung+m14",
        isBest: false,
      },
    ],
    priceHistory: [
      { week: 1, amazon: 14999, flipkart: 14499 },
      { week: 2, amazon: 14499, flipkart: 13999 },
      { week: 3, amazon: 13999, flipkart: 13499 },
      { week: 4, amazon: 13499, flipkart: 12999 },
      { week: 5, amazon: 12999, flipkart: 12499 },
      { week: 6, amazon: 12999, flipkart: 12499 },
      { week: 7, amazon: 12999, flipkart: 12499 },
      { week: 8, amazon: 12999, flipkart: 12499 },
    ],
    sabsastaScore: {
      total: 88,
      priceScore: 92,
      qualityScore: 82,
      reliabilityScore: 88,
      experienceScore: 84,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Price is at all-time low. Best budget Samsung under ₹13K.",
      confidence: 89,
      priceTrend: "STABLE",
      belowAverage: true,
    },
    youtubeReviews: [
      {
        channel: "Trakin Tech",
        views: "2.2M",
        sentiment: 83,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=samsung+m14+review",
      },
      {
        channel: "Beebom",
        views: "780K",
        sentiment: 80,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=samsung+m14+beebom",
      },
    ],
  },
  {
    id: "iqoo-z9",
    name: "iQOO Z9 (8GB/128GB)",
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80",
    category: "Smartphones",
    platforms: [
      {
        platform: "Flipkart",
        price: 18999,
        originalPrice: 22999,
        deliveryTime: "2 days",
        deliveryFee: 0,
        rating: 4.5,
        inStock: true,
        link: "https://www.flipkart.com/search?q=iqoo+z9",
        isBest: true,
      },
      {
        platform: "Amazon",
        price: 19999,
        originalPrice: 22999,
        deliveryTime: "1 day",
        deliveryFee: 0,
        rating: 4.5,
        inStock: true,
        link: "https://www.amazon.in/s?k=iqoo+z9",
        isBest: false,
      },
    ],
    priceHistory: [
      { week: 1, amazon: 22999, flipkart: 21999 },
      { week: 2, amazon: 21999, flipkart: 20999 },
      { week: 3, amazon: 20999, flipkart: 19999 },
      { week: 4, amazon: 20499, flipkart: 19499 },
      { week: 5, amazon: 19999, flipkart: 18999 },
      { week: 6, amazon: 19999, flipkart: 18999 },
      { week: 7, amazon: 19999, flipkart: 18999 },
      { week: 8, amazon: 19999, flipkart: 18999 },
    ],
    sabsastaScore: {
      total: 93,
      priceScore: 95,
      qualityScore: 92,
      reliabilityScore: 90,
      experienceScore: 91,
      label: "Excellent Value",
      color: "green",
    },
    aiRecommendation: {
      action: "BUY NOW",
      reason: "Best performance phone under ₹20K. Price stable at low.",
      confidence: 85,
      priceTrend: "STABLE",
      belowAverage: true,
    },
    youtubeReviews: [
      {
        channel: "Geeky Ranjit",
        views: "2.8M",
        sentiment: 94,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=iqoo+z9+review",
      },
      {
        channel: "Technical Guruji",
        views: "3.4M",
        sentiment: 91,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=iqoo+z9+technical+guruji",
      },
      {
        channel: "Trakin Tech",
        views: "1.6M",
        sentiment: 90,
        isSponsored: false,
        link: "https://www.youtube.com/results?search_query=iqoo+z9+trakin",
      },
    ],
  },
]