import { RideOption } from "@/types"

export const RIDES: Record<string, RideOption[]> = {
  "koramangala-airport": [
    {
      id: "rapido-bike-1",
      platform: "Rapido",
      type: "Rapido Bike",
      category: "bike",
      price: 89,
      eta: 4,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://rapido.bike",
      platformColor: "#22C55E",
      sabsastaScore: {
        total: 91, priceScore: 98, qualityScore: 82,
        reliabilityScore: 88, experienceScore: 85,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "uber-moto-1",
      platform: "Uber",
      type: "Uber Moto",
      category: "bike",
      price: 112,
      eta: 6,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://m.uber.com/ul/",
      platformColor: "#000000",
      sabsastaScore: {
        total: 82, priceScore: 84, qualityScore: 86,
        reliabilityScore: 88, experienceScore: 85,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "ola-auto-1",
      platform: "Ola",
      type: "Ola Auto",
      category: "auto",
      price: 149,
      eta: 3,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://www.olacabs.com",
      platformColor: "#EAB308",
      sabsastaScore: {
        total: 86, priceScore: 88, qualityScore: 84,
        reliabilityScore: 85, experienceScore: 82,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "uber-auto-1",
      platform: "Uber",
      type: "Uber Auto",
      category: "auto",
      price: 162,
      eta: 5,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://m.uber.com/ul/",
      platformColor: "#000000",
      sabsastaScore: {
        total: 83, priceScore: 82, qualityScore: 86,
        reliabilityScore: 88, experienceScore: 85,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "ola-mini-1",
      platform: "Ola",
      type: "Ola Mini",
      category: "cab",
      price: 389,
      eta: 6,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://www.olacabs.com",
      platformColor: "#EAB308",
      sabsastaScore: {
        total: 84, priceScore: 86, qualityScore: 84,
        reliabilityScore: 82, experienceScore: 80,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "uber-go-1",
      platform: "Uber",
      type: "Uber Go",
      category: "cab",
      price: 520,
      eta: 5,
      surgeMultiplier: 1.4,
      hasSurge: true,
      bookLink: "https://m.uber.com/ul/",
      platformColor: "#000000",
      sabsastaScore: {
        total: 68, priceScore: 58, qualityScore: 88,
        reliabilityScore: 90, experienceScore: 88,
        label: "Good Value", color: "orange",
      },
    },
    {
      id: "ola-prime-1",
      platform: "Ola",
      type: "Ola Prime",
      category: "cab",
      price: 449,
      eta: 8,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://www.olacabs.com",
      platformColor: "#EAB308",
      sabsastaScore: {
        total: 80, priceScore: 78, qualityScore: 86,
        reliabilityScore: 84, experienceScore: 82,
        label: "Good Value", color: "orange",
      },
    },
    {
      id: "uber-black-1",
      platform: "Uber",
      type: "Uber Black",
      category: "premium",
      price: 890,
      eta: 10,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://m.uber.com/ul/",
      platformColor: "#000000",
      sabsastaScore: {
        total: 72, priceScore: 55, qualityScore: 96,
        reliabilityScore: 95, experienceScore: 94,
        label: "Good Value", color: "orange",
      },
    },
  ],
  "bandra-andheri": [
    {
      id: "rapido-bike-2",
      platform: "Rapido",
      type: "Rapido Bike",
      category: "bike",
      price: 49,
      eta: 3,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://rapido.bike",
      platformColor: "#22C55E",
      sabsastaScore: {
        total: 93, priceScore: 99, qualityScore: 82,
        reliabilityScore: 88, experienceScore: 85,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "ola-auto-2",
      platform: "Ola",
      type: "Ola Auto",
      category: "auto",
      price: 89,
      eta: 4,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://www.olacabs.com",
      platformColor: "#EAB308",
      sabsastaScore: {
        total: 88, priceScore: 92, qualityScore: 84,
        reliabilityScore: 85, experienceScore: 82,
        label: "Excellent Value", color: "green",
      },
    },
    {
      id: "uber-go-2",
      platform: "Uber",
      type: "Uber Go",
      category: "cab",
      price: 142,
      eta: 5,
      surgeMultiplier: 1.2,
      hasSurge: true,
      bookLink: "https://m.uber.com/ul/",
      platformColor: "#000000",
      sabsastaScore: {
        total: 74, priceScore: 68, qualityScore: 88,
        reliabilityScore: 90, experienceScore: 88,
        label: "Good Value", color: "orange",
      },
    },
    {
      id: "ola-mini-2",
      platform: "Ola",
      type: "Ola Mini",
      category: "cab",
      price: 129,
      eta: 6,
      surgeMultiplier: 1.0,
      hasSurge: false,
      bookLink: "https://www.olacabs.com",
      platformColor: "#EAB308",
      sabsastaScore: {
        total: 85, priceScore: 88, qualityScore: 84,
        reliabilityScore: 82, experienceScore: 80,
        label: "Excellent Value", color: "green",
      },
    },
  ],
}

export function getRides(from: string, to: string): RideOption[] {
  const key = `${from.toLowerCase()}-${to.toLowerCase()}`
  return (
    RIDES[key] ||
    RIDES["koramangala-airport"] // fallback to default
  )
}